import type { BiologyExperiment, Organelle3D } from '../types/biology.types';
import type { HeartPart } from '../composables/biology/useHeartGLB';

const heartOrganelles: Organelle3D[] = [
  {
    id: 'leftAtrium',
    nameKey: 'biology.heart.leftAtrium.name',
    descriptionKey: 'biology.heart.leftAtrium.description',
    longDescriptionKey: 'biology.heart.leftAtrium.longDescription',
    factsKeys: [
      'biology.heart.leftAtrium.fact1',
      'biology.heart.leftAtrium.fact2',
      'biology.heart.leftAtrium.fact3',
    ],
    geometry: 'sphere',
    size: 0.9,
    position: [-1.2, 1.4, 0.2],
    color: '#ef4444',
    opacity: 0.85,
    explodeVector: [-1.5, 1.5, 0.5],
    hotspotPosition: [-1.2, 2.2, 0.2],
  },
  {
    id: 'rightAtrium',
    nameKey: 'biology.heart.rightAtrium.name',
    descriptionKey: 'biology.heart.rightAtrium.description',
    longDescriptionKey: 'biology.heart.rightAtrium.longDescription',
    factsKeys: [
      'biology.heart.rightAtrium.fact1',
      'biology.heart.rightAtrium.fact2',
      'biology.heart.rightAtrium.fact3',
    ],
    geometry: 'sphere',
    size: 0.85,
    position: [1.2, 1.4, 0.2],
    color: '#3b82f6',
    opacity: 0.85,
    explodeVector: [1.5, 1.5, 0.5],
    hotspotPosition: [1.2, 2.2, 0.2],
  },
  {
    id: 'leftVentricle',
    nameKey: 'biology.heart.leftVentricle.name',
    descriptionKey: 'biology.heart.leftVentricle.description',
    longDescriptionKey: 'biology.heart.leftVentricle.longDescription',
    factsKeys: [
      'biology.heart.leftVentricle.fact1',
      'biology.heart.leftVentricle.fact2',
      'biology.heart.leftVentricle.fact3',
    ],
    geometry: 'sphere',
    size: 1.2,
    position: [-1.1, -0.8, 0.3],
    color: '#dc2626',
    opacity: 0.9,
    explodeVector: [-1.8, -1.5, 0.8],
    hotspotPosition: [-1.1, -1.7, 0.3],
  },
  {
    id: 'rightVentricle',
    nameKey: 'biology.heart.rightVentricle.name',
    descriptionKey: 'biology.heart.rightVentricle.description',
    longDescriptionKey: 'biology.heart.rightVentricle.longDescription',
    factsKeys: [
      'biology.heart.rightVentricle.fact1',
      'biology.heart.rightVentricle.fact2',
      'biology.heart.rightVentricle.fact3',
    ],
    geometry: 'sphere',
    size: 1.05,
    position: [1.1, -0.8, 0.3],
    color: '#2563eb',
    opacity: 0.9,
    explodeVector: [1.8, -1.5, 0.8],
    hotspotPosition: [1.1, -1.7, 0.3],
  },
  {
    id: 'aorta',
    nameKey: 'biology.heart.aorta.name',
    descriptionKey: 'biology.heart.aorta.description',
    longDescriptionKey: 'biology.heart.aorta.longDescription',
    factsKeys: [
      'biology.heart.aorta.fact1',
      'biology.heart.aorta.fact2',
      'biology.heart.aorta.fact3',
    ],
    geometry: 'tube',
    size: 0.35,
    position: [-0.6, 2.2, 0],
    rotation: [0, 0, 0.6],
    color: '#b91c1c',
    opacity: 1,
    explodeVector: [-0.5, 2.5, 0],
    hotspotPosition: [-0.6, 2.9, 0],
    path: [
      [0, 0, 0],
      [0, 0.6, 0],
      [0.4, 1.0, 0],
      [1.2, 1.0, 0],
    ],
  },
  {
    id: 'septum',
    nameKey: 'biology.heart.septum.name',
    descriptionKey: 'biology.heart.septum.description',
    longDescriptionKey: 'biology.heart.septum.longDescription',
    factsKeys: [
      'biology.heart.septum.fact1',
      'biology.heart.septum.fact2',
      'biology.heart.septum.fact3',
    ],
    geometry: 'box',
    size: 0.25,
    position: [0, 0.2, 0.2],
    color: '#9ca3af',
    opacity: 0.75,
    explodeVector: [0, 0, 1.5],
    hotspotPosition: [0, 0.2, 1.2],
    selectable: false,
  },
];

export const heartExperiment: BiologyExperiment = {
  id: 'heart',
  titleKey: 'biology.heartTitle',
  subtitleKey: 'biology.heartSubtitle',
  icon: '🫀',
  organelles: heartOrganelles,
};

export const heartParts: HeartPart[] = [
  {
    id: 'leftAtrium',
    nameKey: 'biology.heart.leftAtrium.name',
    descriptionKey: 'biology.heart.leftAtrium.description',
    longDescriptionKey: 'biology.heart.leftAtrium.longDescription',
    factsKeys: [
      'biology.heart.leftAtrium.fact1',
      'biology.heart.leftAtrium.fact2',
      'biology.heart.leftAtrium.fact3',
    ],
    position: [-1.2, 3.8, 0.8],
  },
  {
    id: 'rightAtrium',
    nameKey: 'biology.heart.rightAtrium.name',
    descriptionKey: 'biology.heart.rightAtrium.description',
    longDescriptionKey: 'biology.heart.rightAtrium.longDescription',
    factsKeys: [
      'biology.heart.rightAtrium.fact1',
      'biology.heart.rightAtrium.fact2',
      'biology.heart.rightAtrium.fact3',
    ],
    position: [1.2, 3.8, 0.8],
  },
  {
    id: 'leftVentricle',
    nameKey: 'biology.heart.leftVentricle.name',
    descriptionKey: 'biology.heart.leftVentricle.description',
    longDescriptionKey: 'biology.heart.leftVentricle.longDescription',
    factsKeys: [
      'biology.heart.leftVentricle.fact1',
      'biology.heart.leftVentricle.fact2',
      'biology.heart.leftVentricle.fact3',
    ],
    position: [-1.3, 0.5, 0.6],
  },
  {
    id: 'rightVentricle',
    nameKey: 'biology.heart.rightVentricle.name',
    descriptionKey: 'biology.heart.rightVentricle.description',
    longDescriptionKey: 'biology.heart.rightVentricle.longDescription',
    factsKeys: [
      'biology.heart.rightVentricle.fact1',
      'biology.heart.rightVentricle.fact2',
      'biology.heart.rightVentricle.fact3',
    ],
    position: [1.3, 0.5, 0.6],
  },
  {
    id: 'septum',
    nameKey: 'biology.heart.septum.name',
    descriptionKey: 'biology.heart.septum.description',
    longDescriptionKey: 'biology.heart.septum.longDescription',
    factsKeys: [
      'biology.heart.septum.fact1',
      'biology.heart.septum.fact2',
      'biology.heart.septum.fact3',
    ],
    position: [0, 2.2, 0.8],
  },
  {
    id: 'aorticValve',
    nameKey: 'biology.heart.aorticValve.name',
    descriptionKey: 'biology.heart.aorticValve.description',
    longDescriptionKey: 'biology.heart.aorticValve.longDescription',
    factsKeys: [
      'biology.heart.aorticValve.fact1',
      'biology.heart.aorticValve.fact2',
      'biology.heart.aorticValve.fact3',
    ],
    position: [-0.5, 2.6, 0.3],
  },
  {
    id: 'mitralValve',
    nameKey: 'biology.heart.mitralValve.name',
    descriptionKey: 'biology.heart.mitralValve.description',
    longDescriptionKey: 'biology.heart.mitralValve.longDescription',
    factsKeys: [
      'biology.heart.mitralValve.fact1',
      'biology.heart.mitralValve.fact2',
      'biology.heart.mitralValve.fact3',
    ],
    position: [-1.1, 1.3, 0.4],
  },
  {
    id: 'pulmonaryValve',
    nameKey: 'biology.heart.pulmonaryValve.name',
    descriptionKey: 'biology.heart.pulmonaryValve.description',
    longDescriptionKey: 'biology.heart.pulmonaryValve.longDescription',
    factsKeys: [
      'biology.heart.pulmonaryValve.fact1',
      'biology.heart.pulmonaryValve.fact2',
      'biology.heart.pulmonaryValve.fact3',
    ],
    position: [0.5, 2.4, 0.3],
  },
  {
    id: 'tricuspidValve',
    nameKey: 'biology.heart.tricuspidValve.name',
    descriptionKey: 'biology.heart.tricuspidValve.description',
    longDescriptionKey: 'biology.heart.tricuspidValve.longDescription',
    factsKeys: [
      'biology.heart.tricuspidValve.fact1',
      'biology.heart.tricuspidValve.fact2',
      'biology.heart.tricuspidValve.fact3',
    ],
    position: [1.1, 1.3, 0.4],
  },
];
