import type { BiologyExperiment } from '../types/biology.types';

export const animalCellExperiment: BiologyExperiment = {
  id: 'animal-cell',
  titleKey: 'biology.animalCellTitle',
  subtitleKey: 'biology.animalCellSubtitle',
  icon: '🧬',
  organelles: [
    {
      id: 'cell-membrane',
      nameKey: 'biology.organelle.membrane.name',
      descriptionKey: 'biology.organelle.membrane.description',
      longDescriptionKey: 'biology.organelle.membrane.longDescription',
      factsKeys: ['biology.organelle.membrane.fact1', 'biology.organelle.membrane.fact2', 'biology.organelle.membrane.fact3'],
      geometry: 'sphere',
      size: 5,
      position: [0, 0, 0],
      color: '#93c5fd',
      opacity: 0.45,
      explodeVector: [0, 0, 0],
      hotspotPosition: [0, 3.2, 0],
      blocksRaycast: true,
      renderMode: 'wireframe',
    },
    {
      id: 'cytoplasm',
      nameKey: 'biology.organelle.cytoplasm.name',
      descriptionKey: 'biology.organelle.cytoplasm.description',
      geometry: 'sphere',
      size: 4.85,
      position: [0, 0, 0],
      color: '#1d4ed8',
      opacity: 0.12,
      explodeVector: [0, 0, 0],
      hotspotPosition: [0, 0, 0],
      selectable: false,
      blocksRaycast: true,
    },
    {
      id: 'nucleus',
      nameKey: 'biology.organelle.nucleus.name',
      descriptionKey: 'biology.organelle.nucleus.description',
      longDescriptionKey: 'biology.organelle.nucleus.longDescription',
      factsKeys: ['biology.organelle.nucleus.fact1', 'biology.organelle.nucleus.fact2', 'biology.organelle.nucleus.fact3'],
      geometry: 'sphere',
      size: 1.4,
      position: [0, 0, 0],
      color: '#a855f7',
      opacity: 0.95,
      explodeVector: [0, 0, 0],
      hotspotPosition: [0, 1.6, 0],
    },
    {
      id: 'mitochondrion-1',
      nameKey: 'biology.organelle.mitochondrion.name',
      descriptionKey: 'biology.organelle.mitochondrion.description',
      longDescriptionKey: 'biology.organelle.mitochondrion.longDescription',
      factsKeys: ['biology.organelle.mitochondrion.fact1', 'biology.organelle.mitochondrion.fact2', 'biology.organelle.mitochondrion.fact3'],
      geometry: 'capsule',
      size: 0.45,
      position: [1.8, 0.6, 0.8],
      rotation: [0, 0, Math.PI / 4],
      color: '#ef4444',
      opacity: 0.9,
      explodeVector: [1.5, 0.8, 0.8],
      hotspotPosition: [1.8, 1.2, 0.8],
    },
    {
      id: 'endoplasmic-reticulum',
      nameKey: 'biology.organelle.endoplasmicReticulum.name',
      descriptionKey: 'biology.organelle.endoplasmicReticulum.description',
      longDescriptionKey: 'biology.organelle.endoplasmicReticulum.longDescription',
      factsKeys: ['biology.organelle.endoplasmicReticulum.fact1', 'biology.organelle.endoplasmicReticulum.fact2', 'biology.organelle.endoplasmicReticulum.fact3'],
      geometry: 'tube',
      size: 0.25,
      position: [0.8, 1.2, -1],
      rotation: [0, Math.PI / 5, -Math.PI / 8],
      color: '#f59e0b',
      opacity: 0.85,
      explodeVector: [1.2, 1.6, -1.2],
      hotspotPosition: [0.8, 1.8, -1],
    },
    {
      id: 'ribosomes',
      nameKey: 'biology.organelle.ribosomes.name',
      descriptionKey: 'biology.organelle.ribosomes.description',
      longDescriptionKey: 'biology.organelle.ribosomes.longDescription',
      factsKeys: ['biology.organelle.ribosomes.fact1', 'biology.organelle.ribosomes.fact2', 'biology.organelle.ribosomes.fact3'],
      geometry: 'particles',
      size: 0.12,
      position: [0, 0, 0],
      color: '#10b981',
      opacity: 0.9,
      explodeVector: [0, 0, 0],
      hotspotPosition: [-1.2, 2.2, 0.6],
    },
  ],
};

export const biologyExperiments: BiologyExperiment[] = [animalCellExperiment];
