import type { ModelPart } from '../composables/biology/useGLBModel';

export const brainGLBParts: ModelPart[] = [
  {
    id: 'cerebrum',
    nameKey: 'biology.brain.cerebrum.name',
    descriptionKey: 'biology.brain.cerebrum.description',
    longDescriptionKey: 'biology.brain.cerebrum.longDescription',
    factsKeys: [
      'biology.brain.cerebrum.fact1',
      'biology.brain.cerebrum.fact2',
      'biology.brain.cerebrum.fact3',
    ],
    position: [0, 0, 0],
    meshNames: ['Brain', 'Brain-Inner'],
  },
  {
    id: 'cerebellum',
    nameKey: 'biology.brain.cerebellum.name',
    descriptionKey: 'biology.brain.cerebellum.description',
    longDescriptionKey: 'biology.brain.cerebellum.longDescription',
    factsKeys: [
      'biology.brain.cerebellum.fact1',
      'biology.brain.cerebellum.fact2',
      'biology.brain.cerebellum.fact3',
    ],
    position: [0, -1.2, -1.8],
    meshNames: ['Cerebellum', 'Lingula of cerebellum', 'Tonsil of cerebellum'],
  },
  {
    id: 'brainstem',
    nameKey: 'biology.brain.brainstem.name',
    descriptionKey: 'biology.brain.brainstem.description',
    longDescriptionKey: 'biology.brain.brainstem.longDescription',
    factsKeys: [
      'biology.brain.brainstem.fact1',
      'biology.brain.brainstem.fact2',
      'biology.brain.brainstem.fact3',
    ],
    position: [0, -2.8, -0.8],
    meshNames: ['Midbrain', 'Pons', 'Pyramid of medulla oblongata'],
  },
  {
    id: 'frontalLobe',
    nameKey: 'biology.brain.frontalLobe.name',
    descriptionKey: 'biology.brain.frontalLobe.description',
    longDescriptionKey: 'biology.brain.frontalLobe.longDescription',
    factsKeys: [
      'biology.brain.frontalLobe.fact1',
      'biology.brain.frontalLobe.fact2',
      'biology.brain.frontalLobe.fact3',
    ],
    position: [0, 0.5, 2.2],
    meshNames: [
      'Superior frontal gyrus',
      'Middle frontal gyrus',
      'Inferior frontal sulcus',
      'Opercular part of inferior frontal gyrus',
      'Triangular part of inferior frontal gyrus',
      'Orbital part of  inferior frontal gyrus',
      'Superior frontal sulcus',
    ],
  },
  {
    id: 'temporalLobe',
    nameKey: 'biology.brain.temporalLobe.name',
    descriptionKey: 'biology.brain.temporalLobe.description',
    longDescriptionKey: 'biology.brain.temporalLobe.longDescription',
    factsKeys: [
      'biology.brain.temporalLobe.fact1',
      'biology.brain.temporalLobe.fact2',
      'biology.brain.temporalLobe.fact3',
    ],
    position: [-2.8, -0.5, 0.5],
    meshNames: [
      'Temporal lobe',
      'Superior temporal gyrus (Lateral part)',
      'Middle temporal gyrus',
      'Inferior temporal gyrus',
      'Temporal pole',
      'Temporal plane',
      'Superior temporal sulcus',
      'Inferior temporal sulcus',
    ],
  },
  {
    id: 'parietalLobe',
    nameKey: 'biology.brain.parietalLobe.name',
    descriptionKey: 'biology.brain.parietalLobe.description',
    longDescriptionKey: 'biology.brain.parietalLobe.longDescription',
    factsKeys: [
      'biology.brain.parietalLobe.fact1',
      'biology.brain.parietalLobe.fact2',
      'biology.brain.parietalLobe.fact3',
    ],
    position: [0, 1.8, -0.5],
    meshNames: [
      'Superior parietal lobule',
      'Intraparietal sulcus',
      'Subparietal sulcus',
    ],
  },
  {
    id: 'occipitalLobe',
    nameKey: 'biology.brain.occipitalLobe.name',
    descriptionKey: 'biology.brain.occipitalLobe.description',
    longDescriptionKey: 'biology.brain.occipitalLobe.longDescription',
    factsKeys: [
      'biology.brain.occipitalLobe.fact1',
      'biology.brain.occipitalLobe.fact2',
      'biology.brain.occipitalLobe.fact3',
    ],
    position: [0, 0, -2.8],
    meshNames: [
      'Superior occipital gyri',
      'Lateral occipital gyrus (Middle occipital gyrus*)',
      'Occipital pole',
      'Inferior occipital gyrus and sulcus*',
    ],
  },
  {
    id: 'hippocampus',
    nameKey: 'biology.brain.hippocampus.name',
    descriptionKey: 'biology.brain.hippocampus.description',
    longDescriptionKey: 'biology.brain.hippocampus.longDescription',
    factsKeys: [
      'biology.brain.hippocampus.fact1',
      'biology.brain.hippocampus.fact2',
      'biology.brain.hippocampus.fact3',
    ],
    position: [0, -0.5, 0],
    meshNames: ['Hippocampus'],
  },
  {
    id: 'corpusCallosum',
    nameKey: 'biology.brain.corpusCallosum.name',
    descriptionKey: 'biology.brain.corpusCallosum.description',
    longDescriptionKey: 'biology.brain.corpusCallosum.longDescription',
    factsKeys: [
      'biology.brain.corpusCallosum.fact1',
      'biology.brain.corpusCallosum.fact2',
      'biology.brain.corpusCallosum.fact3',
    ],
    position: [0, 0.5, 0],
    meshNames: ['Corpus callosum'],
  },
  {
    id: 'ventricles',
    nameKey: 'biology.brain.ventricles.name',
    descriptionKey: 'biology.brain.ventricles.description',
    longDescriptionKey: 'biology.brain.ventricles.longDescription',
    factsKeys: [
      'biology.brain.ventricles.fact1',
      'biology.brain.ventricles.fact2',
      'biology.brain.ventricles.fact3',
    ],
    position: [0, 0, 0],
    meshNames: ['Lateral ventricle', 'Third ventricle', 'Fourth ventricle'],
  },
];
