import type { ModelPart } from '../composables/biology/useGLBModel';

export const brainGLBParts: ModelPart[] = [
  {
    id: 'cerebrum',
    nameKey: 'biology.brain.cerebrum.name',
    descriptionKey: 'biology.brain.cerebrum.description',
    longDescriptionKey: 'biology.brain.cerebrum.longDescription',
    factsKeys: [
      'biology.brain.cerebrum.fact1',
      'biology.brain.cerebrum.fact2',
      'biology.brain.cerebrum.fact3',
    ],
    position: [0, 0, 0],
    meshNames: [
      'Allen_white_matter_of_forebrain_L', 'Allen_white_matter_of_forebrain_R',
      'Allen_head_of_caudate_L', 'Allen_head_of_caudate_R',
      'Allen_body_of_caudate_L', 'Allen_body_of_caudate_R',
      'Allen_tail_of_caudate_L', 'Allen_tail_of_caudate_R',
      'Allen_putamen_L', 'Allen_putamen_R',
      'Allen_nucleus_accumbens_L', 'Allen_nucleus_accumbens_R',
      'Allen_external_segment_of_globus_pallidus_L', 'Allen_external_segment_of_globus_pallidus_R',
      'Allen_internal_segment_of_globus_pallidus_L', 'Allen_internal_segment_of_globus_pallidus_R',
      'Allen_claustrum_L', 'Allen_claustrum_R',
      'Allen_basal_forebrain_L', 'Allen_basal_forebrain_R',
      'Allen_septal_nuclei_L', 'Allen_septal_nuclei_R',
      'Allen_thalamus_L', 'Allen_thalamus_R',
      'Allen_amygdaloid_complex_L', 'Allen_amygdaloid_complex_R',
      'Allen_hypothalamus_L', 'Allen_hypothalamus_R',
      'Allen_cingulate_gyrus_rostral_anterior_part_L', 'Allen_cingulate_gyrus_rostral_anterior_part_R',
      'Allen_cingulate_gyrus_caudal_posterior_part_L', 'Allen_cingulate_gyrus_caudal_posterior_part_R',
      'Allen_long_insular_gyri_L', 'Allen_long_insular_gyri_R',
      'Allen_short_insular_gyri_L', 'Allen_short_insular_gyri_R',
      'VH_F_optic_chiasm',
    ],
  },
  {
    id: 'cerebellum',
    nameKey: 'biology.brain.cerebellum.name',
    descriptionKey: 'biology.brain.cerebellum.description',
    longDescriptionKey: 'biology.brain.cerebellum.longDescription',
    factsKeys: [
      'biology.brain.cerebellum.fact1',
      'biology.brain.cerebellum.fact2',
      'biology.brain.cerebellum.fact3',
    ],
    position: [0, -1.2, -1.8],
    meshNames: [
      'Allen_cerebellar_vermis_L', 'Allen_cerebellar_vermis_R',
      'Allen_cerebellar_deep_nuclei_L', 'Allen_cerebellar_deep_nuclei_R',
      'Allen_lateral_hemisphere_of_cerebellum_L', 'Allen_lateral_hemisphere_of_cerebellum_R',
      'Allen_paravermis_of_cerebellum_L', 'Allen_paravermis_of_cerebellum_R',
      'Allen_white_matter_of_hindbrain_L', 'Allen_white_matter_of_hindbrain_R',
      'Allen_superior_cerebellar_peduncle_brachium_conjunctivum_L', 'Allen_superior_cerebellar_peduncle_brachium_conjunctivum_R',
      'Allen_middle_cerebellar_peduncle_L', 'Allen_middle_cerebellar_peduncle_R',
      'Allen_inferior_cerebellar_peduncle_L', 'Allen_inferior_cerebellar_peduncle_R',
    ],
  },
  {
    id: 'brainstem',
    nameKey: 'biology.brain.brainstem.name',
    descriptionKey: 'biology.brain.brainstem.description',
    longDescriptionKey: 'biology.brain.brainstem.longDescription',
    factsKeys: [
      'biology.brain.brainstem.fact1',
      'biology.brain.brainstem.fact2',
      'biology.brain.brainstem.fact3',
    ],
    position: [0, -2.8, -0.8],
    meshNames: [
      'Allen_basilar_part_of_pons_L', 'Allen_basilar_part_of_pons_R',
      'Allen_pontine_tegmentum_L', 'Allen_pontine_tegmentum_R',
      'Allen_pyramidal_part_of_medulla_oblongata_L', 'Allen_pyramidal_part_of_medulla_oblongata_R',
      'Allen_tegmentum_of_medulla_oblongata_L', 'Allen_tegmentum_of_medulla_oblongata_R',
      'Allen_inferior_olive_L', 'Allen_inferior_olive_R',
      'Allen_midbrain_tegmentum_L', 'Allen_midbrain_tegmentum_R',
      'Allen_cerebral_peduncle_crus_cerebri_L', 'Allen_cerebral_peduncle_crus_cerebri_R',
      'Allen_red_nucleus_L', 'Allen_red_nucleus_R',
      'Allen_substantia_nigra_L', 'Allen_substantia_nigra_R',
      'Allen_superior_colliculus_L', 'Allen_superior_colliculus_R',
      'Allen_inferior_colliculus_L', 'Allen_inferior_colliculus_R',
      'Allen_pretectal_region_L', 'Allen_pretectal_region_R',
      'Allen_cerebral_aqueduct_L', 'Allen_cerebral_aqueduct_R',
      'Allen_central_canal_of_medulla_oblongata_L', 'Allen_central_canal_of_medulla_oblongata_R',
    ],
  },
  {
    id: 'frontalLobe',
    nameKey: 'biology.brain.frontalLobe.name',
    descriptionKey: 'biology.brain.frontalLobe.description',
    longDescriptionKey: 'biology.brain.frontalLobe.longDescription',
    factsKeys: [
      'biology.brain.frontalLobe.fact1',
      'biology.brain.frontalLobe.fact2',
      'biology.brain.frontalLobe.fact3',
    ],
    position: [0, 0.5, 2.2],
    meshNames: [
      'Allen_precentral_gyrus_L', 'Allen_precentral_gyrus_R',
      'Allen_superior_frontal_gyrus_L', 'Allen_superior_frontal_gyrus_R',
      'Allen_middle_frontal_gyrus_L', 'Allen_middle_frontal_gyrus_R',
      'Allen_inferior_frontal_gyrus_triangular_part_L', 'Allen_inferior_frontal_gyrus_triangular_part_R',
      'Allen_inferior_frontal_gyrus_opercular_part_L', 'Allen_inferior_frontal_gyrus_opercular_part_R',
      'Allen_gyrus_rectus_straight_gyrus_L', 'Allen_gyrus_rectus_straight_gyrus_R',
      'Allen_medial_orbital_gyrus_L', 'Allen_medial_orbital_gyrus_R',
      'Allen_anterior_intermediate_orbital_gyrus_L', 'Allen_anterior_intermediate_orbital_gyrus_R',
      'Allen_posterior_intermediate_orbital_gyrus_L', 'Allen_posterior_intermediate_orbital_gyrus_R',
      'Allen_lateral_orbital_gyrus_L', 'Allen_lateral_orbital_gyrus_R',
      'Allen_paracentral_lobule_rostral_part_L', 'Allen_paracentral_lobule_rostral_part_R',
      'Allen_frontal_operculum_L', 'Allen_frontal_operculum_R',
      'Allen_frontal_pole_L', 'Allen_frontal_pole_R',
      'Allen_frontomarginal_gyrus_L', 'Allen_frontomarginal_gyrus_R',
      'Allen_rostral_gyrus_L', 'Allen_rostral_gyrus_R',
      'Allen_subcallosal_gyrus_parolfactory_gyrus_L', 'Allen_subcallosal_gyrus_parolfactory_gyrus_R',
      'Allen_paracingulate_gyrus_L', 'Allen_paracingulate_gyrus_R',
    ],
  },
  {
    id: 'temporalLobe',
    nameKey: 'biology.brain.temporalLobe.name',
    descriptionKey: 'biology.brain.temporalLobe.description',
    longDescriptionKey: 'biology.brain.temporalLobe.longDescription',
    factsKeys: [
      'biology.brain.temporalLobe.fact1',
      'biology.brain.temporalLobe.fact2',
      'biology.brain.temporalLobe.fact3',
    ],
    position: [-2.8, -0.5, 0.5],
    meshNames: [
      'Allen_superior_temporal_gyrus_L', 'Allen_superior_temporal_gyrus_R',
      'Allen_middle_temporal_gyrus_L', 'Allen_middle_temporal_gyrus_R',
      'Allen_inferior_temporal_gyrus_L', 'Allen_inferior_temporal_gyrus_R',
      'Allen_occipitotemporal_fusiform_gyrus_temporal_part_L', 'Allen_occipitotemporal_fusiform_gyrus_temporal_part_R',
      'Allen_transverse_temporal_gyrus_Heschls_gyrus_L', 'Allen_transverse_temporal_gyrus_Heschls_gyrus_R',
      'Allen_planum_temporale_L', 'Allen_planum_temporale_R',
      'Allen_planum_polare_L', 'Allen_planum_polare_R',
      'Allen_temporal_pole_L', 'Allen_temporal_pole_R',
      'Allen_anterior_parahippocampal_gyrus_L', 'Allen_anterior_parahippocampal_gyrus_R',
      'Allen_posterior_parahippocampal_gyrus_L', 'Allen_posterior_parahippocampal_gyrus_R',
      'Allen_gyrus_ambiens_L', 'Allen_gyrus_ambiens_R',
      'Allen_ingulo_parahippocampal_isthmus_L', 'Allen_ingulo_parahippocampal_isthmus_R',
    ],
  },
  {
    id: 'parietalLobe',
    nameKey: 'biology.brain.parietalLobe.name',
    descriptionKey: 'biology.brain.parietalLobe.description',
    longDescriptionKey: 'biology.brain.parietalLobe.longDescription',
    factsKeys: [
      'biology.brain.parietalLobe.fact1',
      'biology.brain.parietalLobe.fact2',
      'biology.brain.parietalLobe.fact3',
    ],
    position: [0, 1.8, -0.5],
    meshNames: [
      'Allen_postcentral_gyrus_L', 'Allen_postcentral_gyrus_R',
      'Allen_supraparietal_lobule_L', 'Allen_supraparietal_lobule_R',
      'Allen_supramarginal_gyrus_L', 'Allen_supramarginal_gyrus_R',
      'Allen_angular_gyrus_L', 'Allen_angular_gyrus_R',
      'Allen_precuneus_L', 'Allen_precuneus_R',
      'Allen_paracentral_lobule_caudal_part_L', 'Allen_paracentral_lobule_caudal_part_R',
      'Allen_parietal_operculum_L', 'Allen_parietal_operculum_R',
    ],
  },
  {
    id: 'occipitalLobe',
    nameKey: 'biology.brain.occipitalLobe.name',
    descriptionKey: 'biology.brain.occipitalLobe.description',
    longDescriptionKey: 'biology.brain.occipitalLobe.longDescription',
    factsKeys: [
      'biology.brain.occipitalLobe.fact1',
      'biology.brain.occipitalLobe.fact2',
      'biology.brain.occipitalLobe.fact3',
    ],
    position: [0, 0, -2.8],
    meshNames: [
      'Allen_occipital_pole_L', 'Allen_occipital_pole_R',
      'Allen_cuneus_L', 'Allen_cuneus_R',
      'Allen_lingual_gyrus_medial_occipitotemporal_gyrus_L', 'Allen_lingual_gyrus_medial_occipitotemporal_gyrus_R',
      'Allen_lateral_occipitotemporal_fusiform_gyrus_occipital_part_L', 'Allen_lateral_occipitotemporal_fusiform_gyrus_occipital_part_R',
      'Allen_inferior_occipital_gyrus_L', 'Allen_inferior_occipital_gyrus_R',
      'Allen_superior_occipital_gyrus_L', 'Allen_superior_occipital_gyrus_R',
    ],
  },
  {
    id: 'hippocampus',
    nameKey: 'biology.brain.hippocampus.name',
    descriptionKey: 'biology.brain.hippocampus.description',
    longDescriptionKey: 'biology.brain.hippocampus.longDescription',
    factsKeys: [
      'biology.brain.hippocampus.fact1',
      'biology.brain.hippocampus.fact2',
      'biology.brain.hippocampus.fact3',
    ],
    position: [0, -0.5, 0],
    meshNames: [
      'Allen_head_of_hippocampus_L', 'Allen_head_of_hippocampus_R',
      'Allen_body_of_hippocampus_L', 'Allen_body_of_hippocampus_R',
      'Allen_tail_of_hippocampus_L', 'Allen_tail_of_hippocampus_R',
    ],
  },
  {
    id: 'corpusCallosum',
    nameKey: 'biology.brain.corpusCallosum.name',
    descriptionKey: 'biology.brain.corpusCallosum.description',
    longDescriptionKey: 'biology.brain.corpusCallosum.longDescription',
    factsKeys: [
      'biology.brain.corpusCallosum.fact1',
      'biology.brain.corpusCallosum.fact2',
      'biology.brain.corpusCallosum.fact3',
    ],
    position: [0, 0.5, 0],
    meshNames: [
      'Allen_corpus_callosum_L', 'Allen_corpus_callosum_R',
      'Allen_anterior_commissure_L', 'Allen_anterior_commissure_R',
      'Allen_fornix_L', 'Allen_fornix_R',
      'Allen_mammillothalamic_tract_L', 'Allen_mammillothalamic_tract_R',
      'Allen_optic_tract_L', 'Allen_optic_tract_R',
      'Allen_optic_radiation_L', 'Allen_optic_radiation_R',
    ],
  },
  {
    id: 'ventricles',
    nameKey: 'biology.brain.ventricles.name',
    descriptionKey: 'biology.brain.ventricles.description',
    longDescriptionKey: 'biology.brain.ventricles.longDescription',
    factsKeys: [
      'biology.brain.ventricles.fact1',
      'biology.brain.ventricles.fact2',
      'biology.brain.ventricles.fact3',
    ],
    position: [0, 0, 0],
    meshNames: [
      'Allen_anterior_horn_of_lateral_ventricle_L', 'Allen_anterior_horn_of_lateral_ventricle_R',
      'Allen_body_of_lateral_ventricle_L', 'Allen_body_of_lateral_ventricle_R',
      'Allen_posterior_horn_of_lateral_ventricle_L', 'Allen_posterior_horn_of_lateral_ventricle_R',
      'Allen_inferior_horn_of_lateral_ventricle_L', 'Allen_inferior_horn_of_lateral_ventricle_R',
      'Allen_atrium_of_lateral_ventricle_L', 'Allen_atrium_of_lateral_ventricle_R',
      'Allen_third_ventricle_L', 'Allen_third_ventricle_R',
      'Allen_fourth_ventricle_L', 'Allen_fourth_ventricle_R',
    ],
  },
];
