import type { ModelPart } from '../composables/biology/useGLBModel';

export const digestiveParts: ModelPart[] = [
  {
    id: 'liver',
    nameKey: 'biology.anatomy.digestive.liver.title',
    descriptionKey: 'biology.anatomy.digestive.liver.description',
    longDescriptionKey: 'biology.anatomy.digestive.liver.longDescription',
    factsKeys: [
      'biology.anatomy.digestive.liver.fact1',
      'biology.anatomy.digestive.liver.fact2',
      'biology.anatomy.digestive.liver.fact3',
    ],
    position: [0, 0.1, 0],
    namePatterns: ['liver_'],
    excludePatterns: [],
  },
  {
    id: 'gallbladder',
    nameKey: 'biology.anatomy.digestive.gallbladder.title',
    descriptionKey: 'biology.anatomy.digestive.gallbladder.description',
    longDescriptionKey: 'biology.anatomy.digestive.gallbladder.longDescription',
    factsKeys: [
      'biology.anatomy.digestive.gallbladder.fact1',
      'biology.anatomy.digestive.gallbladder.fact2',
      'biology.anatomy.digestive.gallbladder.fact3',
    ],
    position: [0, 0.05, 0],
    namePatterns: ['gallbladder_'],
    excludePatterns: [],
  },
  {
    id: 'stomach',
    nameKey: 'biology.anatomy.digestive.stomach.title',
    descriptionKey: 'biology.anatomy.digestive.stomach.description',
    longDescriptionKey: 'biology.anatomy.digestive.stomach.longDescription',
    factsKeys: [
      'biology.anatomy.digestive.stomach.fact1',
      'biology.anatomy.digestive.stomach.fact2',
      'biology.anatomy.digestive.stomach.fact3',
    ],
    position: [0, 0.02, 0],
    namePatterns: ['stomach_'],
    excludePatterns: [],
  },
  {
    id: 'smallIntestine',
    nameKey: 'biology.anatomy.digestive.smallIntestine.title',
    descriptionKey: 'biology.anatomy.digestive.smallIntestine.description',
    longDescriptionKey: 'biology.anatomy.digestive.smallIntestine.longDescription',
    factsKeys: [
      'biology.anatomy.digestive.smallIntestine.fact1',
      'biology.anatomy.digestive.smallIntestine.fact2',
      'biology.anatomy.digestive.smallIntestine.fact3',
    ],
    position: [0, -0.05, 0],
    namePatterns: ['small_intestine_'],
    excludePatterns: [],
  },
  {
    id: 'largeIntestine',
    nameKey: 'biology.anatomy.digestive.largeIntestine.title',
    descriptionKey: 'biology.anatomy.digestive.largeIntestine.description',
    longDescriptionKey: 'biology.anatomy.digestive.largeIntestine.longDescription',
    factsKeys: [
      'biology.anatomy.digestive.largeIntestine.fact1',
      'biology.anatomy.digestive.largeIntestine.fact2',
      'biology.anatomy.digestive.largeIntestine.fact3',
    ],
    position: [0, -0.1, 0],
    namePatterns: ['large_intestine_'],
    excludePatterns: [],
  },
  {
    id: 'spleen',
    nameKey: 'biology.anatomy.digestive.spleen.title',
    descriptionKey: 'biology.anatomy.digestive.spleen.description',
    longDescriptionKey: 'biology.anatomy.digestive.spleen.longDescription',
    factsKeys: [
      'biology.anatomy.digestive.spleen.fact1',
      'biology.anatomy.digestive.spleen.fact2',
      'biology.anatomy.digestive.spleen.fact3',
    ],
    position: [0, 0.05, 0],
    namePatterns: ['spleen_'],
    excludePatterns: [],
  },
  {
    id: 'pancreas',
    nameKey: 'biology.anatomy.digestive.pancreas.title',
    descriptionKey: 'biology.anatomy.digestive.pancreas.description',
    longDescriptionKey: 'biology.anatomy.digestive.pancreas.longDescription',
    factsKeys: [
      'biology.anatomy.digestive.pancreas.fact1',
      'biology.anatomy.digestive.pancreas.fact2',
      'biology.anatomy.digestive.pancreas.fact3',
    ],
    position: [0, 0, 0],
    namePatterns: ['pancreas_'],
    excludePatterns: [],
  },
];
