import type { ModelPart } from '../composables/biology/useGLBModel';

export const eyeParts: ModelPart[] = [
  {
    id: 'cornea',
    nameKey: 'biology.anatomy.eye.cornea.title',
    descriptionKey: 'biology.anatomy.eye.cornea.description',
    longDescriptionKey: 'biology.anatomy.eye.cornea.longDescription',
    factsKeys: [
      'biology.anatomy.eye.cornea.fact1',
      'biology.anatomy.eye.cornea.fact2',
      'biology.anatomy.eye.cornea.fact3',
    ],
    position: [0, 0, 0],
    meshNames: ['VH_F_cornea_R'],
    dimOpacity: 0.03,
  },
  {
    id: 'lens',
    nameKey: 'biology.anatomy.eye.lens.title',
    descriptionKey: 'biology.anatomy.eye.lens.description',
    longDescriptionKey: 'biology.anatomy.eye.lens.longDescription',
    factsKeys: [
      'biology.anatomy.eye.lens.fact1',
      'biology.anatomy.eye.lens.fact2',
      'biology.anatomy.eye.lens.fact3',
    ],
    position: [0, 0, 0],
    meshNames: ['VH_F_lens_R', 'VH_F_suspensory_ligament_of_lens_R'],
    dimOpacity: 0.06,
  },
  {
    id: 'iris',
    nameKey: 'biology.anatomy.eye.iris.title',
    descriptionKey: 'biology.anatomy.eye.iris.description',
    longDescriptionKey: 'biology.anatomy.eye.iris.longDescription',
    factsKeys: [
      'biology.anatomy.eye.iris.fact1',
      'biology.anatomy.eye.iris.fact2',
      'biology.anatomy.eye.iris.fact3',
    ],
    position: [0, 0, 0],
    meshNames: ['VH_F_iris_R', 'VH_F_pupil_R'],
    dimOpacity: 0.15,
  },
  {
    id: 'retina',
    nameKey: 'biology.anatomy.eye.retina.title',
    descriptionKey: 'biology.anatomy.eye.retina.description',
    longDescriptionKey: 'biology.anatomy.eye.retina.longDescription',
    factsKeys: [
      'biology.anatomy.eye.retina.fact1',
      'biology.anatomy.eye.retina.fact2',
      'biology.anatomy.eye.retina.fact3',
    ],
    position: [0, 0, 0],
    meshNames: ['VH_F_retina_R', 'VH_F_fovea_R', 'VH_F_macula_lutea_R', 'VH_F_optic_disc_R', 'VH_F_ora_serrata_of_retina_R'],
    dimOpacity: 0.12,
  },
  {
    id: 'opticNerve',
    nameKey: 'biology.anatomy.eye.opticNerve.title',
    descriptionKey: 'biology.anatomy.eye.opticNerve.description',
    longDescriptionKey: 'biology.anatomy.eye.opticNerve.longDescription',
    factsKeys: [
      'biology.anatomy.eye.opticNerve.fact1',
      'biology.anatomy.eye.opticNerve.fact2',
      'biology.anatomy.eye.opticNerve.fact3',
    ],
    position: [0, 0, 0],
    meshNames: ['VH_F_optic_disc_R'],
    dimOpacity: 0.2,
  },
  {
    id: 'sclera',
    nameKey: 'biology.anatomy.eye.sclera.title',
    descriptionKey: 'biology.anatomy.eye.sclera.description',
    longDescriptionKey: 'biology.anatomy.eye.sclera.longDescription',
    factsKeys: [
      'biology.anatomy.eye.sclera.fact1',
      'biology.anatomy.eye.sclera.fact2',
      'biology.anatomy.eye.sclera.fact3',
    ],
    position: [0, 0, 0],
    meshNames: ['VH_F_sclera_R', 'VH_F_bulbar_conjunctiva_R', 'VH_F_corneo_scleral_junction_R'],
    dimOpacity: 0.08,
  },
  {
    id: 'choroid',
    nameKey: 'biology.anatomy.eye.choroid.title',
    descriptionKey: 'biology.anatomy.eye.choroid.description',
    longDescriptionKey: 'biology.anatomy.eye.choroid.longDescription',
    factsKeys: [
      'biology.anatomy.eye.choroid.fact1',
      'biology.anatomy.eye.choroid.fact2',
      'biology.anatomy.eye.choroid.fact3',
    ],
    position: [0, 0, 0],
    meshNames: ['VH_F_optic_choroid_R'],
    dimOpacity: 0.1,
  },
  {
    id: 'vitreous',
    nameKey: 'biology.anatomy.eye.vitreous.title',
    descriptionKey: 'biology.anatomy.eye.vitreous.description',
    longDescriptionKey: 'biology.anatomy.eye.vitreous.longDescription',
    factsKeys: [
      'biology.anatomy.eye.vitreous.fact1',
      'biology.anatomy.eye.vitreous.fact2',
      'biology.anatomy.eye.vitreous.fact3',
    ],
    position: [0, 0, 0],
    meshNames: ['VH_F_vitreous_humor_R', 'VH_F_aqueous_humor_R'],
    dimOpacity: 0.02,
  },
];
