import type { ModelPart } from '../composables/biology/useGLBModel';

export const kidneyParts: ModelPart[] = [
  {
    id: 'cortex',
    nameKey: 'biology.anatomy.kidney.cortex.title',
    descriptionKey: 'biology.anatomy.kidney.cortex.description',
    longDescriptionKey: 'biology.anatomy.kidney.cortex.longDescription',
    factsKeys: [
      'biology.anatomy.kidney.cortex.fact1',
      'biology.anatomy.kidney.cortex.fact2',
      'biology.anatomy.kidney.cortex.fact3',
    ],
    position: [0.8, 0, 0],
    namePatterns: ['Object_3', 'Object_6', 'Object_8', 'Object_30'],
    excludePatterns: [],
  },
  {
    id: 'medulla',
    nameKey: 'biology.anatomy.kidney.medulla.title',
    descriptionKey: 'biology.anatomy.kidney.medulla.description',
    longDescriptionKey: 'biology.anatomy.kidney.medulla.longDescription',
    factsKeys: [
      'biology.anatomy.kidney.medulla.fact1',
      'biology.anatomy.kidney.medulla.fact2',
      'biology.anatomy.kidney.medulla.fact3',
    ],
    position: [0.57, 0, 0],
    namePatterns: ['Object_0', 'Object_1', 'Object_4', 'Object_7', 'Object_9', 'Object_10', 'Object_11', 'Object_14', 'Object_16', 'Object_17', 'Object_18'],
    excludePatterns: [],
  },
  {
    id: 'renalColumn',
    nameKey: 'biology.anatomy.kidney.renalColumn.title',
    descriptionKey: 'biology.anatomy.kidney.renalColumn.description',
    longDescriptionKey: 'biology.anatomy.kidney.renalColumn.longDescription',
    factsKeys: [
      'biology.anatomy.kidney.renalColumn.fact1',
      'biology.anatomy.kidney.renalColumn.fact2',
      'biology.anatomy.kidney.renalColumn.fact3',
    ],
    position: [0.58, 0, 0],
    namePatterns: ['Object_2', 'Object_5', 'Object_13', 'Object_22', 'Object_24'],
    excludePatterns: [],
  },
  {
    id: 'calyces',
    nameKey: 'biology.anatomy.kidney.calyces.title',
    descriptionKey: 'biology.anatomy.kidney.calyces.description',
    longDescriptionKey: 'biology.anatomy.kidney.calyces.longDescription',
    factsKeys: [
      'biology.anatomy.kidney.calyces.fact1',
      'biology.anatomy.kidney.calyces.fact2',
      'biology.anatomy.kidney.calyces.fact3',
    ],
    position: [0.58, -0.2, 0],
    namePatterns: ['Object_12', 'Object_20', 'Object_26', 'Object_28'],
    excludePatterns: [],
  },
  {
    id: 'pelvis',
    nameKey: 'biology.anatomy.kidney.pelvis.title',
    descriptionKey: 'biology.anatomy.kidney.pelvis.description',
    longDescriptionKey: 'biology.anatomy.kidney.pelvis.longDescription',
    factsKeys: [
      'biology.anatomy.kidney.pelvis.fact1',
      'biology.anatomy.kidney.pelvis.fact2',
      'biology.anatomy.kidney.pelvis.fact3',
    ],
    position: [0.58, -0.1, 0],
    namePatterns: ['Object_23', 'Object_27'],
    excludePatterns: [],
  },
  {
    id: 'artery',
    nameKey: 'biology.anatomy.kidney.artery.title',
    descriptionKey: 'biology.anatomy.kidney.artery.description',
    longDescriptionKey: 'biology.anatomy.kidney.artery.longDescription',
    factsKeys: [
      'biology.anatomy.kidney.artery.fact1',
      'biology.anatomy.kidney.artery.fact2',
      'biology.anatomy.kidney.artery.fact3',
    ],
    position: [0.58, 0.35, -0.13],
    namePatterns: ['Object_25'],
    excludePatterns: [],
  },
  {
    id: 'vein',
    nameKey: 'biology.anatomy.kidney.vein.title',
    descriptionKey: 'biology.anatomy.kidney.vein.description',
    longDescriptionKey: 'biology.anatomy.kidney.vein.longDescription',
    factsKeys: [
      'biology.anatomy.kidney.vein.fact1',
      'biology.anatomy.kidney.vein.fact2',
      'biology.anatomy.kidney.vein.fact3',
    ],
    position: [0.67, -0.07, 0.19],
    namePatterns: ['Object_31'],
    excludePatterns: [],
  },
  {
    id: 'nephron',
    nameKey: 'biology.anatomy.kidney.nephron.title',
    descriptionKey: 'biology.anatomy.kidney.nephron.description',
    longDescriptionKey: 'biology.anatomy.kidney.nephron.longDescription',
    factsKeys: [
      'biology.anatomy.kidney.nephron.fact1',
      'biology.anatomy.kidney.nephron.fact2',
      'biology.anatomy.kidney.nephron.fact3',
    ],
    position: [0.58, 0, 0.3],
    namePatterns: ['Object_15', 'Object_19', 'Object_21'],
    excludePatterns: [],
  },
  {
    id: 'ureter',
    nameKey: 'biology.anatomy.kidney.ureter.title',
    descriptionKey: 'biology.anatomy.kidney.ureter.description',
    longDescriptionKey: 'biology.anatomy.kidney.ureter.longDescription',
    factsKeys: [
      'biology.anatomy.kidney.ureter.fact1',
      'biology.anatomy.kidney.ureter.fact2',
      'biology.anatomy.kidney.ureter.fact3',
    ],
    position: [0.6, -0.65, -0.8],
    namePatterns: ['Object_29'],
    excludePatterns: [],
  },
];
