import type { BiologyExperiment } from '../types/biology.types';

export const plantCellExperiment: BiologyExperiment = {
  id: 'plant-cell',
  titleKey: 'biology.plantCellTitle',
  subtitleKey: 'biology.plantCellSubtitle',
  icon: '🌱',
  organelles: [
    {
      id: 'cell-wall',
      nameKey: 'biology.plantOrganelle.cellWall.name',
      descriptionKey: 'biology.plantOrganelle.cellWall.description',
      longDescriptionKey: 'biology.plantOrganelle.cellWall.longDescription',
      factsKeys: [
        'biology.plantOrganelle.cellWall.fact1',
        'biology.plantOrganelle.cellWall.fact2',
        'biology.plantOrganelle.cellWall.fact3',
      ],
      geometry: 'roundedBox',
      size: 5.6,
      position: [0, 0, 0],
      color: '#86efac',
      opacity: 0.35,
      explodeVector: [0, 0, 0],
      hotspotPosition: [0, 3.6, 0],
      blocksRaycast: true,
      renderMode: 'wireframe',
    },
    {
      id: 'cell-membrane',
      nameKey: 'biology.plantOrganelle.membrane.name',
      descriptionKey: 'biology.plantOrganelle.membrane.description',
      longDescriptionKey: 'biology.plantOrganelle.membrane.longDescription',
      factsKeys: [
        'biology.plantOrganelle.membrane.fact1',
        'biology.plantOrganelle.membrane.fact2',
        'biology.plantOrganelle.membrane.fact3',
      ],
      geometry: 'sphere',
      size: 4.8,
      position: [0, 0, 0],
      color: '#93c5fd',
      opacity: 0.4,
      explodeVector: [0, 0, 0],
      hotspotPosition: [0, 3, 0],
      blocksRaycast: true,
      renderMode: 'wireframe',
    },
    {
      id: 'cytoplasm',
      nameKey: 'biology.plantOrganelle.cytoplasm.name',
      descriptionKey: 'biology.plantOrganelle.cytoplasm.description',
      longDescriptionKey: 'biology.plantOrganelle.cytoplasm.longDescription',
      factsKeys: [
        'biology.plantOrganelle.cytoplasm.fact1',
        'biology.plantOrganelle.cytoplasm.fact2',
        'biology.plantOrganelle.cytoplasm.fact3',
      ],
      geometry: 'sphere',
      size: 4.65,
      position: [0, 0, 0],
      color: '#22c55e',
      opacity: 0.1,
      explodeVector: [0, 0, 0],
      hotspotPosition: [0, 0, 0],
      selectable: false,
      blocksRaycast: true,
    },
    {
      id: 'central-vacuole',
      nameKey: 'biology.plantOrganelle.centralVacuole.name',
      descriptionKey: 'biology.plantOrganelle.centralVacuole.description',
      longDescriptionKey: 'biology.plantOrganelle.centralVacuole.longDescription',
      factsKeys: [
        'biology.plantOrganelle.centralVacuole.fact1',
        'biology.plantOrganelle.centralVacuole.fact2',
        'biology.plantOrganelle.centralVacuole.fact3',
      ],
      geometry: 'sphere',
      size: 3.3,
      position: [0, 0, 0],
      color: '#60a5fa',
      opacity: 0.45,
      explodeVector: [0, 0, 0],
      hotspotPosition: [0, 3.2, 0],
    },
    {
      id: 'nucleus',
      nameKey: 'biology.plantOrganelle.nucleus.name',
      descriptionKey: 'biology.plantOrganelle.nucleus.description',
      longDescriptionKey: 'biology.plantOrganelle.nucleus.longDescription',
      factsKeys: [
        'biology.plantOrganelle.nucleus.fact1',
        'biology.plantOrganelle.nucleus.fact2',
        'biology.plantOrganelle.nucleus.fact3',
      ],
      geometry: 'sphere',
      size: 1.1,
      position: [-2, 1.8, 0.9],
      color: '#a855f7',
      opacity: 0.95,
      explodeVector: [-1.2, 0.8, 0.6],
      hotspotPosition: [-2, 2.9, 0.9],
    },
    {
      id: 'chloroplast-1',
      nameKey: 'biology.plantOrganelle.chloroplast.name',
      descriptionKey: 'biology.plantOrganelle.chloroplast.description',
      longDescriptionKey: 'biology.plantOrganelle.chloroplast.longDescription',
      factsKeys: [
        'biology.plantOrganelle.chloroplast.fact1',
        'biology.plantOrganelle.chloroplast.fact2',
        'biology.plantOrganelle.chloroplast.fact3',
      ],
      geometry: 'capsule',
      size: 0.36,
      position: [2.3, 0.2, 1.5],
      rotation: [0, Math.PI / 4, Math.PI / 6],
      color: '#16a34a',
      opacity: 0.95,
      explodeVector: [1.4, 0.1, 0.9],
      hotspotPosition: [2.3, 0.8, 1.5],
    },
    {
      id: 'chloroplast-2',
      nameKey: 'biology.plantOrganelle.chloroplast.name',
      descriptionKey: 'biology.plantOrganelle.chloroplast.description',
      geometry: 'capsule',
      size: 0.36,
      position: [-2.1, -1.2, -1.4],
      rotation: [Math.PI / 6, 0, Math.PI / 3],
      color: '#16a34a',
      opacity: 0.95,
      explodeVector: [-1.3, -0.7, -0.9],
      hotspotPosition: [-2.1, -0.6, -1.4],
      selectable: false,
      blocksRaycast: true,
    },
    {
      id: 'mitochondrion',
      nameKey: 'biology.plantOrganelle.mitochondrion.name',
      descriptionKey: 'biology.plantOrganelle.mitochondrion.description',
      longDescriptionKey: 'biology.plantOrganelle.mitochondrion.longDescription',
      factsKeys: [
        'biology.plantOrganelle.mitochondrion.fact1',
        'biology.plantOrganelle.mitochondrion.fact2',
        'biology.plantOrganelle.mitochondrion.fact3',
      ],
      geometry: 'capsule',
      size: 0.4,
      position: [2.2, -1.5, 0.4],
      rotation: [0, 0, Math.PI / 4],
      color: '#ef4444',
      opacity: 0.9,
      explodeVector: [1.3, -0.9, 0.2],
      hotspotPosition: [2.2, -0.9, 0.4],
    },
    {
      id: 'chloroplast-3',
      nameKey: 'biology.plantOrganelle.chloroplast.name',
      descriptionKey: 'biology.plantOrganelle.chloroplast.description',
      geometry: 'capsule',
      size: 0.36,
      position: [-0.5, 2.2, -1.1],
      rotation: [Math.PI / 5, Math.PI / 3, 0],
      color: '#16a34a',
      opacity: 0.95,
      explodeVector: [-0.3, 1.3, -0.7],
      hotspotPosition: [-0.5, 2.8, -1.1],
      selectable: false,
      blocksRaycast: true,
    },
    {
      id: 'chloroplast-4',
      nameKey: 'biology.plantOrganelle.chloroplast.name',
      descriptionKey: 'biology.plantOrganelle.chloroplast.description',
      geometry: 'capsule',
      size: 0.36,
      position: [1.2, 1.9, -1.6],
      rotation: [Math.PI / 4, 0, Math.PI / 5],
      color: '#16a34a',
      opacity: 0.95,
      explodeVector: [0.8, 1.1, -1.1],
      hotspotPosition: [1.2, 2.5, -1.6],
      selectable: false,
      blocksRaycast: true,
    },
  ],
};
