import type { ModelPart } from '../composables/biology/useGLBModel';

export const skeletonParts: ModelPart[] = [
  {
    id: 'cranium',
    nameKey: 'biology.anatomy.skeleton.cranium.title',
    descriptionKey: 'biology.anatomy.skeleton.cranium.description',
    longDescriptionKey: 'biology.anatomy.skeleton.cranium.longDescription',
    factsKeys: [
      'biology.anatomy.skeleton.cranium.fact1',
      'biology.anatomy.skeleton.cranium.fact2',
      'biology.anatomy.skeleton.cranium.fact3',
    ],
    position: [0, 0.12, 0],
    namePatterns: ['frontal', 'parietal', 'occipital', 'temporal', 'sphenoid', 'ethmoid'],
    excludePatterns: ['muscle', 'tendon', 'nerve', 'artery', 'vein', 'cartilage'],
  },
  {
    id: 'facialBones',
    nameKey: 'biology.anatomy.skeleton.facialBones.title',
    descriptionKey: 'biology.anatomy.skeleton.facialBones.description',
    longDescriptionKey: 'biology.anatomy.skeleton.facialBones.longDescription',
    factsKeys: [
      'biology.anatomy.skeleton.facialBones.fact1',
      'biology.anatomy.skeleton.facialBones.fact2',
      'biology.anatomy.skeleton.facialBones.fact3',
    ],
    position: [0, 0.1, 0.02],
    namePatterns: ['mandible', 'maxilla', 'zygomatic', 'nasal', 'vomer', 'palatine', 'lacrimal', 'concha', 'hyoid'],
    excludePatterns: ['muscle', 'tendon', 'nerve', 'artery', 'vein', 'cartilage'],
  },
  {
    id: 'teeth',
    nameKey: 'biology.anatomy.skeleton.teeth.title',
    descriptionKey: 'biology.anatomy.skeleton.teeth.description',
    longDescriptionKey: 'biology.anatomy.skeleton.teeth.longDescription',
    factsKeys: [
      'biology.anatomy.skeleton.teeth.fact1',
      'biology.anatomy.skeleton.teeth.fact2',
      'biology.anatomy.skeleton.teeth.fact3',
    ],
    position: [0, 0.08, 0.03],
    namePatterns: ['incisor', 'canine', 'molar', 'premolar', 'tooth'],
    excludePatterns: ['muscle', 'tendon', 'nerve', 'artery', 'vein'],
  },
  {
    id: 'earOssicles',
    nameKey: 'biology.anatomy.skeleton.earOssicles.title',
    descriptionKey: 'biology.anatomy.skeleton.earOssicles.description',
    longDescriptionKey: 'biology.anatomy.skeleton.earOssicles.longDescription',
    factsKeys: [
      'biology.anatomy.skeleton.earOssicles.fact1',
      'biology.anatomy.skeleton.earOssicles.fact2',
      'biology.anatomy.skeleton.earOssicles.fact3',
    ],
    position: [0, 0.1, 0.01],
    namePatterns: ['stapes', 'incus', 'malleus'],
    excludePatterns: ['muscle', 'tendon', 'nerve', 'artery', 'vein'],
  },
  {
    id: 'cervicalSpine',
    nameKey: 'biology.anatomy.skeleton.cervicalSpine.title',
    descriptionKey: 'biology.anatomy.skeleton.cervicalSpine.description',
    longDescriptionKey: 'biology.anatomy.skeleton.cervicalSpine.longDescription',
    factsKeys: [
      'biology.anatomy.skeleton.cervicalSpine.fact1',
      'biology.anatomy.skeleton.cervicalSpine.fact2',
      'biology.anatomy.skeleton.cervicalSpine.fact3',
    ],
    position: [0, 0.06, 0],
    namePatterns: ['atlas', 'axis', 'vertebra_c'],
    excludePatterns: ['muscle', 'tendon', 'nerve', 'artery', 'vein'],
  },
  {
    id: 'thoracicSpine',
    nameKey: 'biology.anatomy.skeleton.thoracicSpine.title',
    descriptionKey: 'biology.anatomy.skeleton.thoracicSpine.description',
    longDescriptionKey: 'biology.anatomy.skeleton.thoracicSpine.longDescription',
    factsKeys: [
      'biology.anatomy.skeleton.thoracicSpine.fact1',
      'biology.anatomy.skeleton.thoracicSpine.fact2',
      'biology.anatomy.skeleton.thoracicSpine.fact3',
    ],
    position: [0, 0.02, 0],
    namePatterns: ['vertebra_t'],
    excludePatterns: ['muscle', 'tendon', 'nerve', 'artery', 'vein'],
  },
  {
    id: 'lumbarSpine',
    nameKey: 'biology.anatomy.skeleton.lumbarSpine.title',
    descriptionKey: 'biology.anatomy.skeleton.lumbarSpine.description',
    longDescriptionKey: 'biology.anatomy.skeleton.lumbarSpine.longDescription',
    factsKeys: [
      'biology.anatomy.skeleton.lumbarSpine.fact1',
      'biology.anatomy.skeleton.lumbarSpine.fact2',
      'biology.anatomy.skeleton.lumbarSpine.fact3',
    ],
    position: [0, -0.02, 0],
    namePatterns: ['vertebra_l'],
    excludePatterns: ['muscle', 'tendon', 'nerve', 'artery', 'vein'],
  },
  {
    id: 'sacrum',
    nameKey: 'biology.anatomy.skeleton.sacrum.title',
    descriptionKey: 'biology.anatomy.skeleton.sacrum.description',
    longDescriptionKey: 'biology.anatomy.skeleton.sacrum.longDescription',
    factsKeys: [
      'biology.anatomy.skeleton.sacrum.fact1',
      'biology.anatomy.skeleton.sacrum.fact2',
      'biology.anatomy.skeleton.sacrum.fact3',
    ],
    position: [0, -0.05, 0],
    namePatterns: ['sacrum'],
    excludePatterns: ['muscle', 'tendon', 'nerve', 'artery', 'vein'],
  },
  {
    id: 'ribCage',
    nameKey: 'biology.anatomy.skeleton.ribCage.title',
    descriptionKey: 'biology.anatomy.skeleton.ribCage.description',
    longDescriptionKey: 'biology.anatomy.skeleton.ribCage.longDescription',
    factsKeys: [
      'biology.anatomy.skeleton.ribCage.fact1',
      'biology.anatomy.skeleton.ribCage.fact2',
      'biology.anatomy.skeleton.ribCage.fact3',
    ],
    position: [0, 0, 0],
    namePatterns: ['rib', 'costal_cartilage'],
    excludePatterns: ['muscle', 'tendon', 'nerve', 'artery', 'vein', 'levator'],
  },
  {
    id: 'sternum',
    nameKey: 'biology.anatomy.skeleton.sternum.title',
    descriptionKey: 'biology.anatomy.skeleton.sternum.description',
    longDescriptionKey: 'biology.anatomy.skeleton.sternum.longDescription',
    factsKeys: [
      'biology.anatomy.skeleton.sternum.fact1',
      'biology.anatomy.skeleton.sternum.fact2',
      'biology.anatomy.skeleton.sternum.fact3',
    ],
    position: [0, 0.01, 0.03],
    namePatterns: ['sternum', 'manubrium'],
    excludePatterns: ['muscle', 'tendon', 'nerve', 'artery', 'vein'],
  },
  {
    id: 'shoulderGirdle',
    nameKey: 'biology.anatomy.skeleton.shoulderGirdle.title',
    descriptionKey: 'biology.anatomy.skeleton.shoulderGirdle.description',
    longDescriptionKey: 'biology.anatomy.skeleton.shoulderGirdle.longDescription',
    factsKeys: [
      'biology.anatomy.skeleton.shoulderGirdle.fact1',
      'biology.anatomy.skeleton.shoulderGirdle.fact2',
      'biology.anatomy.skeleton.shoulderGirdle.fact3',
    ],
    position: [0, 0.04, 0],
    namePatterns: ['clavicle', 'scapula'],
    excludePatterns: ['muscle', 'tendon', 'nerve', 'artery', 'vein', 'levator'],
  },
  {
    id: 'arm',
    nameKey: 'biology.anatomy.skeleton.arm.title',
    descriptionKey: 'biology.anatomy.skeleton.arm.description',
    longDescriptionKey: 'biology.anatomy.skeleton.arm.longDescription',
    factsKeys: [
      'biology.anatomy.skeleton.arm.fact1',
      'biology.anatomy.skeleton.arm.fact2',
      'biology.anatomy.skeleton.arm.fact3',
    ],
    position: [0.1, 0, 0],
    namePatterns: ['humerus', '^radius', '^ulna'],
    excludePatterns: ['muscle', 'tendon', 'nerve', 'artery', 'vein', 'bursa', 'sheath', 'head of'],
  },
  {
    id: 'hand',
    nameKey: 'biology.anatomy.skeleton.hand.title',
    descriptionKey: 'biology.anatomy.skeleton.hand.description',
    longDescriptionKey: 'biology.anatomy.skeleton.hand.longDescription',
    factsKeys: [
      'biology.anatomy.skeleton.hand.fact1',
      'biology.anatomy.skeleton.hand.fact2',
      'biology.anatomy.skeleton.hand.fact3',
    ],
    position: [0.15, -0.05, 0],
    namePatterns: ['metacarpal', 'capitate', 'hamate', 'lunate', 'pisiform', 'scaphoid', 'trapezium', 'trapezoid', 'triquetrum', 'phalanx_of_hand'],
    excludePatterns: ['muscle', 'tendon', 'nerve', 'artery', 'vein', 'bursa', 'sheath', 'foot'],
  },
  {
    id: 'pelvis',
    nameKey: 'biology.anatomy.skeleton.pelvis.title',
    descriptionKey: 'biology.anatomy.skeleton.pelvis.description',
    longDescriptionKey: 'biology.anatomy.skeleton.pelvis.longDescription',
    factsKeys: [
      'biology.anatomy.skeleton.pelvis.fact1',
      'biology.anatomy.skeleton.pelvis.fact2',
      'biology.anatomy.skeleton.pelvis.fact3',
    ],
    position: [0, -0.04, 0],
    namePatterns: ['hip_bone'],
    excludePatterns: ['muscle', 'tendon', 'nerve', 'artery', 'vein'],
  },
  {
    id: 'leg',
    nameKey: 'biology.anatomy.skeleton.leg.title',
    descriptionKey: 'biology.anatomy.skeleton.leg.description',
    longDescriptionKey: 'biology.anatomy.skeleton.leg.longDescription',
    factsKeys: [
      'biology.anatomy.skeleton.leg.fact1',
      'biology.anatomy.skeleton.leg.fact2',
      'biology.anatomy.skeleton.leg.fact3',
    ],
    position: [0.05, -0.1, 0],
    namePatterns: ['femur', 'tibia', 'fibula', 'patella'],
    excludePatterns: ['muscle', 'tendon', 'nerve', 'artery', 'vein', 'bursa', 'sheath', 'head of'],
  },
  {
    id: 'foot',
    nameKey: 'biology.anatomy.skeleton.foot.title',
    descriptionKey: 'biology.anatomy.skeleton.foot.description',
    longDescriptionKey: 'biology.anatomy.skeleton.foot.longDescription',
    factsKeys: [
      'biology.anatomy.skeleton.foot.fact1',
      'biology.anatomy.skeleton.foot.fact2',
      'biology.anatomy.skeleton.foot.fact3',
    ],
    position: [0.05, -0.15, 0.02],
    namePatterns: ['talus', 'calcaneus', 'navicular', 'cuboid', 'cuneiform', 'metatarsal', 'phalanx_of_foot', 'sesamoid'],
    excludePatterns: ['muscle', 'tendon', 'nerve', 'artery', 'vein', 'bursa', 'sheath', 'hand'],
  },
];
