import type { ChemicalEquation } from './equations-data.js';

export const gasEquations: ChemicalEquation[] = [
  {
    reactants: ['caco3', 'hcl'],
    products: ['cacl2', 'co2', 'water'],
    equation: 'CaCO₃ + 2HCl → CaCl₂ + CO₂↑ + H₂O',
    type: 'gas',
    resultPh: 1.0,
    coefficients: { caco3: 1, hcl: 2 },
    color: '#e0f2fe',
    opacity: 0.4,
    gasEvolution: true,
    gasType: 'CO₂',
    temperatureRise: 2,
  },
  {
    reactants: ['na2co3', 'hcl'],
    products: ['nacl', 'co2', 'water'],
    equation: 'Na₂CO₃ + 2HCl → 2NaCl + CO₂↑ + H₂O',
    type: 'gas',
    resultPh: 1.0,
    coefficients: { na2co3: 1, hcl: 2 },
    color: '#e0f2fe',
    opacity: 0.4,
    gasEvolution: true,
    gasType: 'CO₂',
    temperatureRise: 2,
  },
  {
    reactants: ['nahco3', 'hcl'],
    products: ['nacl', 'co2', 'water'],
    equation: 'NaHCO₃ + HCl → NaCl + CO₂↑ + H₂O',
    type: 'gas',
    resultPh: 1.0,
    color: '#e0f2fe',
    opacity: 0.4,
    gasEvolution: true,
    gasType: 'CO₂',
    temperatureRise: 1,
  },
  {
    reactants: ['zn', 'hcl'],
    products: ['zncl2', 'h2'],
    equation: 'Zn + 2HCl → ZnCl₂ + H₂↑',
    type: 'gas',
    resultPh: 1.0,
    coefficients: { zn: 1, hcl: 2 },
    color: '#e0f2fe',
    opacity: 0.4,
    gasEvolution: true,
    gasType: 'H₂',
    temperatureRise: 8,
  },
  {
    reactants: ['fe', 'hcl'],
    products: ['fecl2', 'h2'],
    equation: 'Fe + 2HCl → FeCl₂ + H₂↑',
    type: 'gas',
    resultPh: 1.0,
    coefficients: { fe: 1, hcl: 2 },
    color: '#e0f2fe',
    opacity: 0.4,
    gasEvolution: true,
    gasType: 'H₂',
    temperatureRise: 6,
  },
  {
    reactants: ['h2so4', 'na2co3'],
    products: ['na2so4', 'co2', 'water'],
    equation: 'H₂SO₄ + Na₂CO₃ → Na₂SO₄ + CO₂↑ + H₂O',
    type: 'gas',
    resultPh: 1.0,
    color: '#e0f2fe',
    opacity: 0.4,
    gasEvolution: true,
    gasType: 'CO₂',
    temperatureRise: 3,
  },
];

export const redoxEquations: ChemicalEquation[] = [
  {
    reactants: ['kmno4', 'h2o2'],
    products: ['mno2', 'o2', 'koh', 'water'],
    equation: '2KMnO₄ + 3H₂O₂ → 2MnO₂ + 3O₂↑ + 2KOH + 2H₂O',
    type: 'redox',
    resultPh: 7.0,
    coefficients: { kmno4: 2, h2o2: 3 },
    color: '#d4a574',
    opacity: 0.5,
    gasEvolution: true,
    gasType: 'O₂',
    precipitate: true,
    precipitateColor: '#5c4033',
    temperatureRise: 10,
  },
  {
    reactants: ['feso4', 'kmno4'],
    products: ['fe2(so4)3', 'mnso4', 'k2so4', 'water'],
    equation: '10FeSO₄ + 2KMnO₄ + 8H₂SO₄ → 5Fe₂(SO₄)₃ + 2MnSO₄ + K₂SO₄ + 8H₂O',
    type: 'redox',
    coefficients: { feso4: 10, kmno4: 2 },
    color: '#fde047',
    opacity: 0.45,
    temperatureRise: 5,
  },
  {
    reactants: ['ki', 'h2o2'],
    products: ['i2', 'koh'],
    equation: '2KI + H₂O₂ → I₂ + 2KOH',
    type: 'redox',
    coefficients: { ki: 2, h2o2: 1 },
    color: '#a16207',
    opacity: 0.5,
    temperatureRise: 4,
  },
];

export const complexEquations: ChemicalEquation[] = [
  {
    reactants: ['cuso4', 'nh3'],
    products: ['cutetrammine'],
    equation: 'CuSO₄ + 4NH₃ → [Cu(NH₃)₄]SO₄',
    type: 'complex',
    coefficients: { cuso4: 1, nh3: 4 },
    color: '#1d4ed8',
    opacity: 0.5,
    temperatureRise: 2,
  },
];
