import type { ChemicalEquation } from './equations-data.js';

export const neutralizationEquations: ChemicalEquation[] = [
  {
    reactants: ['hcl', 'naoh'],
    products: ['nacl', 'water'],
    equation: 'HCl + NaOH → NaCl + H₂O',
    type: 'neutralization',
    resultPh: 7.0,
    color: '#e0f2fe',
    opacity: 0.3,
    temperatureRise: 5,
  },
  {
    reactants: ['h2so4', 'naoh'],
    products: ['na2so4', 'water'],
    equation: 'H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O',
    type: 'neutralization',
    resultPh: 7.0,
    color: '#e0f2fe',
    opacity: 0.3,
    temperatureRise: 8,
    coefficients: { h2so4: 1, naoh: 2 },
  },
  {
    reactants: ['hcl', 'koh'],
    products: ['kcl', 'water'],
    equation: 'HCl + KOH → KCl + H₂O',
    type: 'neutralization',
    resultPh: 7.0,
    color: '#e0f2fe',
    opacity: 0.3,
    temperatureRise: 5,
  },
  {
    reactants: ['ch3cooh', 'naoh'],
    products: ['ch3coona', 'water'],
    equation: 'CH₃COOH + NaOH → CH₃COONa + H₂O',
    type: 'neutralization',
    resultPh: 8.2,
    color: '#fce7f3',
    opacity: 0.35,
    temperatureRise: 3,
  },
  {
    reactants: ['h2so4', 'koh'],
    products: ['k2so4', 'water'],
    equation: 'H₂SO₄ + 2KOH → K₂SO₄ + 2H₂O',
    type: 'neutralization',
    resultPh: 7.0,
    color: '#e0f2fe',
    opacity: 0.3,
    temperatureRise: 7,
    coefficients: { h2so4: 1, koh: 2 },
  },
  {
    reactants: ['hno3', 'naoh'],
    products: ['nano3', 'water'],
    equation: 'HNO₃ + NaOH → NaNO₃ + H₂O',
    type: 'neutralization',
    resultPh: 7.0,
    color: '#e0f2fe',
    opacity: 0.3,
    temperatureRise: 6,
  },
  {
    reactants: ['hcl', 'nh3'],
    products: ['nh4cl'],
    equation: 'HCl + NH₃ → NH₄Cl',
    type: 'neutralization',
    resultPh: 5.5,
    color: '#fef3c7',
    opacity: 0.35,
    temperatureRise: 4,
  },
];

export const precipitationEquations: ChemicalEquation[] = [
  {
    reactants: ['agno3', 'nacl'],
    products: ['agcl', 'nano3'],
    equation: 'AgNO₃ + NaCl → AgCl↓ + NaNO₃',
    type: 'precipitation',
    resultPh: 6.0,
    color: '#e0e7ff',
    opacity: 0.5,
    precipitate: true,
    precipitateColor: '#f1f5f9',
    temperatureRise: 1,
  },
  {
    reactants: ['agno3', 'hcl'],
    products: ['agcl', 'hno3'],
    equation: 'AgNO₃ + HCl → AgCl↓ + HNO₃',
    type: 'precipitation',
    resultPh: 1.0,
    color: '#e0e7ff',
    opacity: 0.5,
    precipitate: true,
    precipitateColor: '#f1f5f9',
    temperatureRise: 1,
  },
  {
    reactants: ['bacl2', 'h2so4'],
    products: ['baso4', 'hcl'],
    equation: 'BaCl₂ + H₂SO₄ → BaSO₄↓ + 2HCl',
    type: 'precipitation',
    resultPh: 1.0,
    color: '#fef9c3',
    opacity: 0.5,
    precipitate: true,
    precipitateColor: '#f1f5f9',
    temperatureRise: 2,
  },
  {
    reactants: ['cuso4', 'naoh'],
    products: ['cuoh2', 'na2so4'],
    equation: 'CuSO₄ + 2NaOH → Cu(OH)₂↓ + Na₂SO₄',
    type: 'precipitation',
    coefficients: { cuso4: 1, naoh: 2 },
    color: '#bae6fd',
    opacity: 0.4,
    precipitate: true,
    precipitateColor: '#1e90ff',
    temperatureRise: 2,
  },
  {
    reactants: ['fecl3', 'naoh'],
    products: ['feoh3', 'nacl'],
    equation: 'FeCl₃ + 3NaOH → Fe(OH)₃↓ + 3NaCl',
    type: 'precipitation',
    coefficients: { fecl3: 1, naoh: 3 },
    color: '#f1f5f9',
    opacity: 0.3,
    precipitate: true,
    precipitateColor: '#b45309',
    temperatureRise: 2,
  },
  {
    reactants: ['pbno3', 'ki'],
    products: ['pbi2', 'kno3'],
    equation: 'Pb(NO₃)₂ + 2KI → PbI₂↓ + 2KNO₃',
    type: 'precipitation',
    coefficients: { pbno3: 1, ki: 2 },
    color: '#f1f5f9',
    opacity: 0.3,
    precipitate: true,
    precipitateColor: '#facc15',
    temperatureRise: 1,
  },
  {
    reactants: ['na2co3', 'cacl2'],
    products: ['caco3', 'nacl'],
    equation: 'Na₂CO₃ + CaCl₂ → CaCO₃↓ + 2NaCl',
    type: 'precipitation',
    color: '#f1f5f9',
    opacity: 0.5,
    precipitate: true,
    precipitateColor: '#e2e8f0',
    temperatureRise: 1,
  },
  {
    reactants: ['mgso4', 'naoh'],
    products: ['mgoh2', 'na2so4'],
    equation: 'MgSO₄ + 2NaOH → Mg(OH)₂↓ + Na₂SO₄',
    type: 'precipitation',
    coefficients: { mgso4: 1, naoh: 2 },
    color: '#ecfccb',
    opacity: 0.5,
    precipitate: true,
    precipitateColor: '#f1f5f9',
    temperatureRise: 1,
  },
  {
    reactants: ['znso4', 'naoh'],
    products: ['znoh2', 'na2so4'],
    equation: 'ZnSO₄ + 2NaOH → Zn(OH)₂↓ + Na₂SO₄',
    type: 'precipitation',
    coefficients: { znso4: 1, naoh: 2 },
    color: '#ecfccb',
    opacity: 0.5,
    precipitate: true,
    precipitateColor: '#f1f5f9',
    temperatureRise: 1,
  },
];
