export const arChemistry = {
  lab: {
    title: 'المختبر الافتراضي',
    reset: 'تصفير المختبر',
    glassware: 'الزجاجيات والأدوات',
    chemicals: 'الرف الكيميائي',
    infoPanel: 'لوحة المعلومات',
    workspace: 'مساحة العمل',
  },
  sections: {
    containers: 'أدوات احتواء السوائل',
    measuring: 'أدوات القياس الدقيق',
    devices: 'أجهزة القياس والتحكم',
    helpers: 'أدوات مساعدة',
    liquids: 'السوائل والأحماض والقواعد',
    solids: 'المواد الصلبة والمساحيق',
    indicators: 'الكواشف والأدلة',
  },
  tools: {
    testTubeSm: 'أنبوب صغير',
    testTubeMd: 'أنبوب متوسط',
    testTubeLg: 'أنبوب كبير',
    beaker100: 'بيكر 100مل',
    beaker250: 'بيكر 250مل',
    beaker500: 'بيكر 500مل',
    erlenmeyer: 'دورق مخروطي',
    volumetricFlask: 'دورق حجمي',
    roundBottomFlask: 'دورق مستدير',
    sepFunnel: 'قمع استخلاص',
    burette: 'سحاحة',
    pipette: 'ماصّة',
    volumetricPipette: 'ماصة حجمية',
    gradCylinder: 'مخبار مدرج',
    bunsenBurner: 'موقد بنسن',
    heatingMantle: 'غطاء تسخين',
    digitalBalance: 'ميزان رقمي',
    phMeter: 'جهاز pH',
    dropper: 'قطّارة',
    spatula: 'ملعقة',
    stirringRod: 'قضيب تحريك',
    testTubeRack: 'حامل أنابيب',
  },
  chemicals: {
    hcl: 'HCl',
    naoh: 'NaOH',
    h2o: 'H₂O',
    caco3: 'CaCO₃',
    mg: 'Mg',
    phenolphthalein: 'فينوفتالين',
    methylOrange: 'ميثيل برتقالي',
  },
  states: {
    empty: 'فارغ',
    full: 'ممتلئ',
    heated: 'مسخّن',
    cooled: 'بارد',
    open: 'مفتوح',
    closed: 'مغلق',
    tared: 'تم التصفير',
  },
  actions: {
    fill: 'تعبئة',
    empty: 'تفريغ',
    refill: 'إعادة تعبئة',
    remove: 'إزالة',
    toggleValve: 'تبديل الصنبور',
    toggleBurner: 'تشغيل/إطفاء',
    tare: 'تصفير',
    enterPour: 'وضع السكب',
    enterPipette: 'وضع الماصة',
    exitPipette: 'إلغاء الماصة',
  },
  units: {
    volume: 'mL',
    weight: 'g',
    temperature: '°C',
    ph: 'pH',
  },
  inspector: {
    title: 'لوحة التحكم',
    volume: 'الحجم',
    color: 'اللون',
    temperature: 'درجة الحرارة',
    ph: 'الرقم الهيدروجيني',
    valveState: 'حالة الصنبور',
    selectTool: 'اضغط على أداة في مساحة العمل لعرض تحكماتها',
  },
  notifications: {
    liquidAdded: 'تم إضافة السائل',
    liquidRemoved: 'تم إزالة السائل',
    heatedTo: 'تم تسخينه إلى',
    cooledTo: 'تم تبريده إلى',
    valveOpened: 'تم فتح الصنبور',
    valveClosed: 'تم إغلاق الصنبور',
  },
} as const;

export type ArChemistry = typeof arChemistry;
