import type { ChemicalEquation } from './chemEquations';

export const gasEquations: ChemicalEquation[] = [
  {
    reactants: ['caco3', 'hcl'],
    products: ['cacl2', 'co2', 'water'],
    equation: 'CaCO₃ + 2HCl → CaCl₂ + CO₂↑ + H₂O',
    type: 'gas',
    resultPh: 1.0,
    color: '#e0f2fe',
    opacity: 0.4,
    gasEvolution: true,
    temperatureRise: 2,
  },
  {
    reactants: ['na2co3', 'hcl'],
    products: ['nacl', 'co2', 'water'],
    equation: 'Na₂CO₃ + 2HCl → 2NaCl + CO₂↑ + H₂O',
    type: 'gas',
    resultPh: 1.0,
    color: '#e0f2fe',
    opacity: 0.4,
    gasEvolution: true,
    temperatureRise: 2,
  },
  {
    reactants: ['nahco3', 'hcl'],
    products: ['nacl', 'co2', 'water'],
    equation: 'NaHCO₃ + HCl → NaCl + CO₂↑ + H₂O',
    type: 'gas',
    resultPh: 1.0,
    color: '#e0f2fe',
    opacity: 0.4,
    gasEvolution: true,
    temperatureRise: 1,
  },
  {
    reactants: ['zn', 'hcl'],
    products: ['zncl2', 'h2'],
    equation: 'Zn + 2HCl → ZnCl₂ + H₂↑',
    type: 'gas',
    resultPh: 1.0,
    color: '#e0f2fe',
    opacity: 0.4,
    gasEvolution: true,
    temperatureRise: 8,
  },
  {
    reactants: ['fe', 'hcl'],
    products: ['fecl2', 'h2'],
    equation: 'Fe + 2HCl → FeCl₂ + H₂↑',
    type: 'gas',
    resultPh: 1.0,
    color: '#e0f2fe',
    opacity: 0.4,
    gasEvolution: true,
    temperatureRise: 6,
  },
  {
    reactants: ['h2so4', 'na2co3'],
    products: ['na2so4', 'co2', 'water'],
    equation: 'H₂SO₄ + Na₂CO₃ → Na₂SO₄ + CO₂↑ + H₂O',
    type: 'gas',
    resultPh: 1.0,
    color: '#e0f2fe',
    opacity: 0.4,
    gasEvolution: true,
    temperatureRise: 3,
  },
];
