import type { ChemicalEquation } from './chemEquations';

export const precipitationEquations: ChemicalEquation[] = [
  {
    reactants: ['agno3', 'nacl'],
    products: ['agcl', 'nano3'],
    equation: 'AgNO₃ + NaCl → AgCl↓ + NaNO₃',
    type: 'precipitation',
    resultPh: 6.0,
    color: '#e0e7ff',
    opacity: 0.5,
    precipitate: true,
    precipitateColor: '#f1f5f9',
    temperatureRise: 1,
  },
  {
    reactants: ['agno3', 'hcl'],
    products: ['agcl', 'hno3'],
    equation: 'AgNO₃ + HCl → AgCl↓ + HNO₃',
    type: 'precipitation',
    resultPh: 1.0,
    color: '#e0e7ff',
    opacity: 0.5,
    precipitate: true,
    precipitateColor: '#f1f5f9',
    temperatureRise: 1,
  },
  {
    reactants: ['bacl2', 'h2so4'],
    products: ['baso4', 'hcl'],
    equation: 'BaCl₂ + H₂SO₄ → BaSO₄↓ + 2HCl',
    type: 'precipitation',
    resultPh: 1.0,
    color: '#fef9c3',
    opacity: 0.5,
    precipitate: true,
    precipitateColor: '#f1f5f9',
    temperatureRise: 2,
  },
  {
    reactants: ['cuso4', 'naoh'],
    products: ['cuoh2', 'na2so4'],
    equation: 'CuSO₄ + 2NaOH → Cu(OH)₂↓ + Na₂SO₄',
    type: 'precipitation',
    color: '#86efac',
    opacity: 0.5,
    precipitate: true,
    precipitateColor: '#15803d',
    temperatureRise: 2,
  },
  {
    reactants: ['fecl3', 'naoh'],
    products: ['feoh3', 'nacl'],
    equation: 'FeCl₃ + 3NaOH → Fe(OH)₃↓ + 3NaCl',
    type: 'precipitation',
    color: '#fca5a5',
    opacity: 0.5,
    precipitate: true,
    precipitateColor: '#7f1d1d',
    temperatureRise: 2,
  },
  {
    reactants: ['pbno3', 'ki'],
    products: ['pbi2', 'kno3'],
    equation: 'Pb(NO₃)₂ + 2KI → PbI₂↓ + 2KNO₃',
    type: 'precipitation',
    color: '#fef08a',
    opacity: 0.5,
    precipitate: true,
    precipitateColor: '#facc15',
    temperatureRise: 1,
  },
  {
    reactants: ['na2co3', 'cacl2'],
    products: ['caco3', 'nacl'],
    equation: 'Na₂CO₃ + CaCl₂ → CaCO₃↓ + 2NaCl',
    type: 'precipitation',
    color: '#f1f5f9',
    opacity: 0.5,
    precipitate: true,
    precipitateColor: '#e2e8f0',
    temperatureRise: 1,
  },
  {
    reactants: ['mgso4', 'naoh'],
    products: ['mgoh2', 'na2so4'],
    equation: 'MgSO₄ + 2NaOH → Mg(OH)₂↓ + Na₂SO₄',
    type: 'precipitation',
    color: '#ecfccb',
    opacity: 0.5,
    precipitate: true,
    precipitateColor: '#84cc16',
    temperatureRise: 1,
  },
  {
    reactants: ['znso4', 'naoh'],
    products: ['znoh2', 'na2so4'],
    equation: 'ZnSO₄ + 2NaOH → Zn(OH)₂↓ + Na₂SO₄',
    type: 'precipitation',
    color: '#ecfccb',
    opacity: 0.5,
    precipitate: true,
    precipitateColor: '#d9f99d',
    temperatureRise: 1,
  },
];
