import type { ChemicalEquation } from './chemEquations';

export const neutralizationEquations: ChemicalEquation[] = [
  {
    reactants: ['hcl', 'naoh'],
    products: ['nacl', 'water'],
    equation: 'HCl + NaOH → NaCl + H₂O',
    type: 'neutralization',
    resultPh: 7.0,
    color: '#e0f2fe',
    opacity: 0.3,
    temperatureRise: 5,
  },
  {
    reactants: ['h2so4', 'naoh'],
    products: ['na2so4', 'water'],
    equation: 'H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O',
    type: 'neutralization',
    resultPh: 7.0,
    color: '#e0f2fe',
    opacity: 0.3,
    temperatureRise: 8,
  },
  {
    reactants: ['hcl', 'koh'],
    products: ['kcl', 'water'],
    equation: 'HCl + KOH → KCl + H₂O',
    type: 'neutralization',
    resultPh: 7.0,
    color: '#e0f2fe',
    opacity: 0.3,
    temperatureRise: 5,
  },
  {
    reactants: ['ch3cooh', 'naoh'],
    products: ['ch3coona', 'water'],
    equation: 'CH₃COOH + NaOH → CH₃COONa + H₂O',
    type: 'neutralization',
    resultPh: 8.2,
    color: '#fce7f3',
    opacity: 0.35,
    temperatureRise: 3,
  },
  {
    reactants: ['h2so4', 'koh'],
    products: ['k2so4', 'water'],
    equation: 'H₂SO₄ + 2KOH → K₂SO₄ + 2H₂O',
    type: 'neutralization',
    resultPh: 7.0,
    color: '#e0f2fe',
    opacity: 0.3,
    temperatureRise: 7,
  },
  {
    reactants: ['hno3', 'naoh'],
    products: ['nano3', 'water'],
    equation: 'HNO₃ + NaOH → NaNO₃ + H₂O',
    type: 'neutralization',
    resultPh: 7.0,
    color: '#e0f2fe',
    opacity: 0.3,
    temperatureRise: 6,
  },
  {
    reactants: ['hcl', 'nh3'],
    products: ['nh4cl', 'water'],
    equation: 'HCl + NH₃ → NH₄Cl',
    type: 'neutralization',
    resultPh: 5.5,
    color: '#fef3c7',
    opacity: 0.35,
    temperatureRise: 4,
  },
];
