-- plans: available subscription packages
CREATE TABLE IF NOT EXISTS plans (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  type TEXT NOT NULL CHECK(type IN ('student','teacher','school')),
  name TEXT NOT NULL,
  price_cents INTEGER NOT NULL,
  billing_interval TEXT NOT NULL CHECK(billing_interval IN ('month','year')),
  currency TEXT NOT NULL DEFAULT 'EUR',
  features TEXT,
  is_active INTEGER DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- subscriptions: current/past subscriptions for users and schools
CREATE TABLE IF NOT EXISTS subscriptions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  owner_id INTEGER NOT NULL,
  owner_type TEXT NOT NULL CHECK(owner_type IN ('user','school')),
  plan_id INTEGER REFERENCES plans(id),
  status TEXT NOT NULL CHECK(status IN ('ACTIVE','TRIAL','EXPIRED','CANCELLED','PENDING')),
  starts_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME,
  last_payment_at DATETIME,
  next_billing_at DATETIME,
  cancelled_at DATETIME,
  payment_provider TEXT,
  payment_reference TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_subscriptions_owner ON subscriptions(owner_id, owner_type, status);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON subscriptions(status);

-- invite_codes: codes generated by schools or teachers for joining
CREATE TABLE IF NOT EXISTS invite_codes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  code TEXT UNIQUE NOT NULL,
  owner_id INTEGER NOT NULL,
  owner_type TEXT NOT NULL CHECK(owner_type IN ('teacher','school')),
  subscription_id INTEGER REFERENCES subscriptions(id),
  max_uses INTEGER,
  used_count INTEGER DEFAULT 0,
  is_active INTEGER DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME
);

CREATE INDEX IF NOT EXISTS idx_invite_codes_code ON invite_codes(code);
CREATE INDEX IF NOT EXISTS idx_invite_codes_owner ON invite_codes(owner_id, owner_type);

-- tenant_memberships: links a user to a school or teacher via an invite code
CREATE TABLE IF NOT EXISTS tenant_memberships (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  member_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  tenant_id INTEGER NOT NULL,
  tenant_type TEXT NOT NULL CHECK(tenant_type IN ('teacher','school')),
  invite_code_id INTEGER REFERENCES invite_codes(id),
  joined_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','suspended','removed')),
  UNIQUE(member_id, tenant_id, tenant_type)
);

CREATE INDEX IF NOT EXISTS idx_tenant_memberships_member ON tenant_memberships(member_id, status);
CREATE INDEX IF NOT EXISTS idx_tenant_memberships_tenant ON tenant_memberships(tenant_id, tenant_type, status);
